object Versions {
    const val legacySupport = "1.0.0"
    const val coreKtx = "1.7.0"
    const val appCompat = "1.4.1"
    const val material = "1.5.0"
    const val constraintLayout = "2.1.3"
    const val navigation = "2.4.1"
    const val hilt = "2.38.1"
    const val gson = "2.8.6"
    const val retrofitVersion = "2.9.0"
    const val loggingInterceptor = "4.9.1"
    const val junit = "4.13.2"
    const val androidxJUnit = "1.1.3"
    const val espressoCore = "3.4.0"
    const val dataStore = "1.0.0"
    const val coroutines = "1.3.5"
    const val javax = "1"
    const val androidxCoreTesting = "2.1.0"
    const val mockWebServer = "4.9.1"
    const val mockK = "1.10.6"
}